"""Daftarkan Frame sebagai kandidat default browser di Windows.

PENTING: script ini TIDAK memaksa Frame jadi default. Windows 10/11
tidak mengizinkan aplikasi mengubah default browser secara otomatis
(perubahan privasi sejak Windows 10 Anniversary Update). Script ini
hanya:

  1. Menulis entry ke HKCU\\Software\\Classes + HKCU\\Software\\Frame
     → supaya Frame MUNCUL di daftar pilihan di Settings.
  2. Menghasilkan file .reg yang bisa di-import user.

Setelah script ini dijalankan, user HARUS:
  1. Import file .reg (double-click).
  2. Buka Settings → Apps → Default apps.
  3. Cari "Frame" → klik → Set default.

Cara pakai:
  python scripts/install_windows_default.py
  (lalu ikuti instruksi di layar)
"""
from __future__ import annotations

import sys
from pathlib import Path


def _is_frozen() -> bool:
    """True kalau dijalankan dari PyInstaller/py2exe bundle."""
    return getattr(sys, "frozen", False)


def _exe_path() -> Path:
    return Path(sys.executable).resolve()


def _dev_pythonw(exe: Path) -> Path:
    """Untuk dev mode, pakai pythonw.exe (tanpa console window)."""
    pythonw = exe.parent / "pythonw.exe"
    return pythonw if pythonw.exists() else exe


def _build_reg_text() -> str:
    exe = _exe_path()
    icon_path = Path(__file__).parent.parent / "frame" / "data" / "ikon.ico"

    if not icon_path.exists():
        print(f"[!] Ikon tidak ditemukan di {icon_path}")
        print("[!] Jalankan konversi PNG → ICO terlebih dahulu:")
        print('[!]   python -c "from PIL import Image; '
              "img = Image.open('frame/data/ikon.png'); "
              "img.save('frame/data/ikon.ico', "
              'sizes=[(16,16),(32,32),(48,48),(64,64),(128,128),(256,256)])"')
        sys.exit(1)

    if _is_frozen():
        cmd = f'\\"{exe}\\" \\"%1\\"'
        mode = "packaged"
    else:
        py = _dev_pythonw(exe)
        cmd = f'\\"{py}\\" -m frame \\"%1\\"'
        mode = "development"

    icon = f'\\"{icon_path}\\",0'

    print(f"[i] Mode: {mode}")
    print(f"[i] Executable: {exe}")
    if not _is_frozen():
        print(f"[i] Launcher: {_dev_pythonw(exe)}")
    print(f"[i] Icon: {icon_path}")
    print()

    return f"""Windows Registry Editor Version 5.00

; Frame - default browser candidate (per-user, no admin needed).
; Generated by scripts/install_windows_default.py.
; After import, go to: Settings > Apps > Default apps > search "Frame".

[HKEY_CURRENT_USER\\Software\\Classes\\FrameHTML]
@="Frame HTML Document"

[HKEY_CURRENT_USER\\Software\\Classes\\FrameHTML\\DefaultIcon]
@={icon}

[HKEY_CURRENT_USER\\Software\\Classes\\FrameHTML\\shell\\open\\command]
@={cmd}

[HKEY_CURRENT_USER\\Software\\Classes\\FrameHTTPS]
@="Frame HTTPS Handler"

[HKEY_CURRENT_USER\\Software\\Classes\\FrameHTTPS\\DefaultIcon]
@={icon}

[HKEY_CURRENT_USER\\Software\\Classes\\FrameHTTPS\\shell\\open\\command]
@={cmd}

[HKEY_CURRENT_USER\\Software\\RegisteredApplications]
"Frame"="Software\\\\Frame\\\\Capabilities"

[HKEY_CURRENT_USER\\Software\\Frame\\Capabilities]
"ApplicationName"="Frame"
"ApplicationDescription"="Lightweight web browser built on PyQt6"
"ApplicationIcon"="{icon_path}"

[HKEY_CURRENT_USER\\Software\\Frame\\Capabilities\\URLAssociations]
"http"="FrameHTTPS"
"https"="FrameHTTPS"

[HKEY_CURRENT_USER\\Software\\Frame\\Capabilities\\FileAssociations]
".html"="FrameHTML"
".htm"="FrameHTML"
"""


def main() -> int:
    if sys.platform != "win32":
        print("[!] Script ini hanya untuk Windows.", file=sys.stderr)
        return 1

    reg_text = _build_reg_text()
    out = Path("frame_default_browser.reg").resolve()
    out.write_text(reg_text, encoding="utf-16")

    print(f"[✓] Registry file dibuat: {out}")
    print()
    print("Langkah selanjutnya (manual — Windows tidak izinkan auto-set):")
    print(f"  1. Double-click '{out.name}' → klik Yes untuk import")
    print("  2. Buka: Settings → Apps → Default apps")
    print("  3. Scroll ke bawah, cari 'Frame', klik")
    print("  4. Klik 'Set default' untuk http & https")
    print()
    print("Setelah itu, klik link dari Slack/WhatsApp/terminal akan")
    print("terbuka di Frame. Frame juga akan muncul sebagai pilihan")
    print("default browser di Settings Windows.")
    return 0


if __name__ == "__main__":
    sys.exit(main())